### ISSUE TITLE
DTC package can't be installed.

### ISSUE THREAD

**Issue by ghost** [srfoster/dtc#10]
Context:
Fresh installation of DrRacket 7.7. Ubuntu 18.04, git.

Issue:
Can't install dtc package because it fails to find 'meta-engine' dependency even when I enable option to automatically resolve the dependencies.

Automatic build of the [package](https://pkgs.racket-lang.org/package/dtc) also [fails](https://pkg-build.racket-lang.org/server/built/fail/dtc.txt) on the racket-lang pkg-build site for the same reason.

Cause:
  [meta-engine](https://pkgs.racket-lang.org/package/meta-engine) is not found on the pgk-build site

Possible solution:
 * Update the [info.rkt](https://github.com/srfoster/dtc/blob/master/info.rkt) file and change the 'meta-engine' dependency from the plain package name to the github page -> https://github.com/thoughtstem/meta-engine.git
 * or register meta-engine as a package on the pkg-build site.

I already tested first solution by cloning this repo, updating the info.rkt file, then removing all user installed packaged from the ide, and installing from the local directory.

Thanks.

**Comment by srfoster** [comment]
Thanks for the report (and for testing a fix)!  I'm looking into it.

**Comment by srfoster** [comment]
After a few fixes to this and a related package, I've managed to get a clean install of `dtc` on my Ubuntu environment.  Thanks again for the report!
