### ISSUE TITLE
Unable to install  dtc package

### ISSUE THREAD

**Issue by marcusyoung** [srfoster/dtc#11]
@srfoster Using Racket 7.7 on Windows 10. I get the following error:

> Resolving "dtc" via https://download.racket-lang.org/releases/7.7/catalog/
> Resolving "dtc" via https://pkgs.racket-lang.org
> Downloading repository https://github.com/srfoster/dtc.git
> bytes->path-element: cannot be converted to a path element
>   path: #"\\"
>   explanation: path can be split, is not relative, or names a special element

**Comment by srfoster** [comment]
Thanks for the report!  I'm looking into it.

**Comment by srfoster** [comment]
After a couple of fixes this this and a related package, I've been able to do a clean install on a Windows machine.  

Thanks again for the report!
