### ISSUE TITLE
Forum Signup Error

### ISSUE THREAD

**Issue by ldhandley** [srfoster/dtc#12]
When you try to signup for the forum, you get to the account created page (https://forum.dont-teach.com/u/account-created) but with this error:
"We cannot detect if your account was created, please ensure you have cookies enabled."

Error has been replicated on multiple machines.

**Comment by srfoster** [comment]
I implemented the fix here: https://meta.discourse.org/t/error-we-cannot-detect-if-your-account-was-created-please-ensure-you-have-cookies-enabled/138317/3

And I was able to get past that account creation step on Chrome/Ubuntu and Chrome/Windows.  I'm closing the ticket for now.  Reopen if you see the issue again.
