### ISSUE TITLE
With OpenGL 2.1 (older hardware) animation doesn't work ("error: GLSL 3.30 is not supported") 

### ISSUE THREAD

**Issue by haijinSk** [srfoster/dtc#14]
Maybe not an issue, only the fact that older versions of OpenGL are not supported by the dtc-animation language. With an older graphics processor integrated onto the motherboard (Intel GMA X4500/OpenGL 2.1), dtc animation doesn't work.

If I run:
#lang dtc/hello/animation
(print "HELLO")

I will get:
"HI
Recompiling sprite db
GL context changed
You are using OpenGL '(2 1) with gl-backend-version of 3.3
Log of shader(1):
	0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
Shader source follows: 
[...]"

PS: I suppose dtc use lux (lux: brilliant interactive programs) for animation, so I have tried the two examples of lux:  https://github.com/jeapostrophe/lux/tree/master/examples
and they worked.

Anyway, thank you for reading this.

**Comment by srfoster** [comment]
Thanks for opening this.  And thanks for testing with `lux`.  We do use lux, but for graphics, we use a package called `mode-lambda`.  If those examples work for you but the `dtc` ones don't, I would suspect there's a bug in `dtc`, and I'll try to track it down. But if `mode-lambda` is also broken, I suspect I'll need to add the system specs you mentioned to a list of unsupported specs.

Thanks again. :)

https://docs.racket-lang.org/mode-lambda/index.html

**Comment by haijinSk** [comment]
I thank you...

So now I had ran: "racket -l mode-lambda/examples/one" to test the mode-lambda and it seems that here is the issue, at least my "OpenGL 2.1" issue, because I have got the "error: GLSL 3.30" message:

"GL context changed
You are using OpenGL '(2 1) with gl-backend-version of 3.3
Log of shader(1):
	0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES
Shader source follows.."

So as you've written, it seems, as a matter of fact, the mode-lambda package simply doesn't support the older version of OpenGL. 

Thank you very much for your time, effort and explanation.
