### ISSUE TITLE
Need to make (animation ...) function for #lang dtc/frames/animations

### ISSUE THREAD

**Issue by ldhandley** [srfoster/dtc#9]
Pg. 122:
```
#lang dtc/frames/animations
(animation
`(1 2 3))
```
Error: `animation: unbound identifier in: animation`

Pg. 123:
```
#lang dtc/frames/animations
(animation
`(3 2 1))
```

**Comment by ldhandley** [comment]
Tried updating dependencies. Was able to update with errors. Now getting this error:
`../../Applications/Racket v7.4/collects/racket/private/kw.rkt:1518:14: application: procedure does not expect an argument with given keyword
  procedure: format-id
  given keyword: #:subs?
  arguments...:
Module Language: invalid language specification in: dtc/frames/animations`

**Comment by ldhandley** [comment]
I installed dtc as specified at the start of the book before starting to test things. Maybe the dtc package isn't installing EVERYTHING people need?

**Comment by srfoster** [comment]
Works for me.  But the function implemented is `animate` not `animation`.  If we need `animation` we can make it an alias for `animate`.  Can you double check?
